### ISSUE TITLE
Code does not work

### ISSUE THREAD

**Issue by iam-zhanghongliang** [zhiqiangdon/CU-Net#10]
Hello, this paper is really good, but I made a mistake when I resurfaced face_prev. I checked a lot of information, but I couldn't solve it. I don't know how to do it, I hope to get help.
Reproduce according to the requirements, the version of python is 2.7, the version of pytorch is 0.1.12, conda 8.0, cudnn 5.1; there is an error when running:
Loading json file is done...
Total training images: 3148
Loading json file is done...
Total validation images: 689
<class 'torch.optim.rmsprop.RMSprop'>
0.00025
Train ia stare ..................
Traceback (most recent call last):
  File "cu-net-face-prev-version.py", line 298, in <module>
    Main()
  File "cu-net-face-prev-version.py", line 129, in main
    Train_loss, train_rmse = train(train_loader, net, optimizer, epoch, visualizer, opt)
  File "cu-net-face-prev-version.py", line 177, in train
    Output = net(img_var)
  File "/share/anaconda2/envs/pytorch0.1.2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    Result = self.forward(*input, **kwargs)
  File "/share/anaconda2/envs/pytorch0.1.2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 61, in forward
    Outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/share/anaconda2/envs/pytorch0.1.2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 71, in parallel_apply
    Return parallel_apply(replicas, inputs, kwargs)
  File "/share/anaconda2/envs/pytorch0.1.2/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 46, in parallel_apply
    Raise output
AttributeError: 'module' object has no attribute '_cudnn_batch_norm_forward'

**Comment by chouqin3** [comment]
> Hello, this paper is really good, but I made a mistake when I resurfaced face_prev. I checked a lot of information, but I couldn't solve it. I don't know how to do it, I hope to get help.
> Reproduce according to the requirements, the version of python is 2.7, the version of pytorch is 0.1.12, conda 8.0, cudnn 5.1; there is an error when running:
> Loading json file is done...
> Total training images: 3148
> Loading json file is done...
> Total validation images: 689
> <class 'torch.optim.rmsprop.RMSprop'>
> 0.00025
> Train ia stare ..................
> Traceback (most recent call last):
>   File "cu-net-face-prev-version.py", line 298, in
>     Main()
>   File "cu-net-face-prev-version.py", line 129, in main
>     Train_loss, train_rmse = train(train_loader, net, optimizer, epoch, visualizer, opt)
>   File "cu-net-face-prev-version.py", line 177, in train
>     Output = net(img_var)
>   File "/share/anaconda2/envs/pytorch0.1.2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in **call**
>     Result = self.forward(*input, **kwargs)
>   File "/share/anaconda2/envs/pytorch0.1.2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 61, in forward
>     Outputs = self.parallel_apply(replicas, inputs, kwargs)
>   File "/share/anaconda2/envs/pytorch0.1.2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 71, in parallel_apply
>     Return parallel_apply(replicas, inputs, kwargs)
>   File "/share/anaconda2/envs/pytorch0.1.2/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 46, in parallel_apply
>     Raise output
> AttributeError: 'module' object has no attribute '_cudnn_batch_norm_forward'

How to solve?
